### ISSUE TITLE
您好，请问有尝试过预训练+Kmeans的方法吗

### ISSUE THREAD

**Issue by Gy915** [thuiar/DeepAligned-Clustering#14]
作者您好，最近在做新意图发现的工作，在复线这篇工作时，我发现直接在预训练模型的基础上+Kmeans在ACC和ARI两个数据上可以达到比预训练+DAC基本上高2-3个点，MNI基本上差不多。目前我也不确定这是否是正常的现象还是我使用有误，如果您之前有类似的经验，希望可以解答一下这个现象，十分感谢！
我的实验设置是banking+0.75（known）+0.1（labeled），K设置为77，对Kmeans的实现方法为直接在ModelManager的train之前调用test函数得到Kmeans结果。

**Comment by Gy915** [comment]
上面说的预训练是指在已知意图数据集上做预训练，也就是Transferring Knowledge from Known Intents 之后的模型做Kmeans

**Comment by HanleiZhang** [comment]
您好，我们也在banking数据集上发现了类似的现象 :)，但是印象中在clinc数据集上是可以比直接k-means预测结果提升很多的。

针对这个问题，我们最近在设计DeepAligned改进算法作为扩展版本，目前已经可以证明改进的DeepAligned算法可以在Banking数据集上解决这个问题（即预训练+第二阶段训练效果较预训练+k-means有明显提升），最新方法代码将会在[TEXTOIR](https://github.com/thuiar/TEXTOIR)平台开源，敬请期待 :)。

**Comment by Gy915** [comment]
感谢您的回复，期待您的新算法:)
