### ISSUE TITLE
what does the DAC method means in your main experiment results?

### ISSUE THREAD

**Issue by skykiseki** [thuiar/DeepAligned-Clustering#15]
doest the DAC means Deep Adaptive Clustering?

paper source like this url: [https://openaccess.thecvf.com/content_ICCV_2017/papers/Chang_Deep_Adaptive_Image_ICCV_2017_paper.pdf](url)

**Comment by HanleiZhang** [comment]
Yes. It means Deep Adaptive Clustering algorithm as mentioned in your link.

**Comment by skykiseki** [comment]
> Yes. It means Deep Adaptive Clustering algorithm as mentioned in your link.

Oh, thanks a lot. Have learned so much from your work.
