### ISSUE TITLE
how to distinguish new intents and old intents(known intents) in the test phase?

### ISSUE THREAD

**Issue by oYoungCo** [thuiar/DeepAligned-Clustering#9]
I'm interested in your work. Please, how to distinguish new intents and old intents(known intents) in the test phase?

**Comment by HanleiZhang** [comment]
Hi, thanks for your attention in our work. In this work, we only evaluate the clustering performance with typical unsupervised clustering metrics, NMI, ARI and ACC (more details can be seen in issue [1](https://github.com/thuiar/DeepAligned-Clustering/issues/1)). By the way, if you are interested in distinguishing the new intents and known intents, you can refer to our another paper "TEXTOIR: An Integrated and Visualized Platform for Text Open Intent Recognition"( [pdf](https://aclanthology.org/2021.acl-demo.20.pdf), [code](https://github.com/thuiar/TEXTOIR) )

**Comment by oYoungCo** [comment]
thank you.
